### ISSUE TITLE
Error in evaluation script

### ISSUE THREAD

**Issue by msd-mohit** [isl-org/StableViewSynthesis#22]
Hi,

Thanks for uploading the code, I tried to run the evaluation script by following the readme:
python exp.py --net resunet3.16_penone.dirs.avg.seq+9+1+unet+5+2+16.single+mlpdir+mean+3+64+16 --cmd eval --iter last --eval-dsets tat-subseq

and got the following error:
[2021-11-18/13:38/INFO/exp]   create target images
Traceback (most recent call last):
  File "exp.py", line 945, in <module>
    worker.do(args, worker_objects)
  File "../co/mytorch.py", line 442, in do
    self.do_cmd(args, worker_objects)
  File "../co/mytorch.py", line 430, in do_cmd
    worker_objects, iters=args.iter, net_root=args.eval_net_root
  File "../co/mytorch.py", line 621, in eval_iters
    self.eval(iter, net, eval_sets)
  File "../co/mytorch.py", line 630, in eval
    self.eval_set(iter, net, eval_set_idx, eval_set, epoch=epoch)
  File "exp.py", line 540, in eval_set
    self.my_eval_set(iter, net, eval_set_idx, eval_set, epoch)
  File "exp.py", line 666, in my_eval_set
    output, self.eval_batch_size, height, width, **self.data
  File "/user/student.aau.dk/mdhaka20/StableViewSynthesis/experiments/modules.py", line 759, in ref_net_forward
    return self.ref_net(ptx, bs, height, width, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/user/student.aau.dk/mdhaka20/StableViewSynthesis/experiments/modules.py", line 477, in forward
    x = torch_scatter.segment_csr(ptx, point_key, reduce="mean")
  File "/usr/local/lib/python3.6/dist-packages/torch_scatter/segment_csr.py", line 103, in segment_csr
    return segment_mean_csr(src, indptr, out)
  File "/usr/local/lib/python3.6/dist-packages/torch_scatter/segment_csr.py", line 18, in segment_mean_csr
    return torch.ops.torch_scatter.segment_mean_csr(src, indptr, out)
RuntimeError: Not compiled with CUDA support

Could you help in this regard?

**Comment by griegler** [comment]
> return torch.ops.torch_scatter.segment_mean_csr(src, indptr, out)
> RuntimeError: Not compiled with CUDA support

Looks like you try to use `torch` with cuda, but the version of PyTorch you are using has no cuda support.

**Comment by msd-mohit** [comment]
Hi, 
Thank you for replying.
I am using the following installations.
    pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
    pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html
    pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html
    pip install torch-geometric

I am still getting the error. I am using CUDA version 11.1
